[pytest]
testpaths = tests
python_files = test_*.py
python_functions = test_*
pythonpath = .
addopts = -v --cov=src --cov=services --cov-report=term-missing --cov-config=pytest.ini
filterwarnings =
    ignore:distutils Version classes are deprecated:DeprecationWarning
    ignore:It is preferred to use 'applyInPandas':UserWarning

[coverage:run]
omit =
    */src/evaluation/*